name: CD Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-app:
    runs-on: [self-hosted, linux, x64]

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Load SSH key (stored in ACTIONS_SSH_KEY)
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY }}

      # 3. Add production server to known_hosts
      - name: Add production host
        run: ssh-keyscan -H ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts || true

      # 4. DockerHub login
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build + push Docker image
      - name: Build and Push Docker Image
        run: |
          DOCKER_REPO=khadijah332/weather-ml-app
          IMAGE_TAG=${{ github.sha }}

          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest

          docker push $DOCKER_REPO:$IMAGE_TAG
          docker push $DOCKER_REPO:latest

      # 6. Copy updated k8s-deployment.yml to production
      - name: Copy Kubernetes Deployment File
        run: |
          echo "Copying deployment file..."
          scp -o StrictHostKeyChecking=no k8s-deployment.yml ubuntu@${{ secrets.PROD_SERVER_IP }}:/tmp/k8s-deployment.yml

          echo "Listing /tmp on server..."
          ssh ubuntu@${{ secrets.PROD_SERVER_IP }} "ls -l /tmp"

      # 7. Run Ansible playbook to redeploy
      - name: Run Ansible Deployment
        run: ansible-playbook -i inventory.ini deploy_k8s.yml
