name: CD Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-app:
    runs-on: [self-hosted, linux, x64]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: SSH setup with secret key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY_TWO }}

      # Step 3: Add Production server to known hosts (ignore errors)
      - name: Add Production server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.218.75.13 >> ~/.ssh/known_hosts || true

      # Step 4: Docker login
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        run: |
          DOCKER_REPO=khadijah332/weather-ml-app
          IMAGE_TAG=${{ github.sha }}
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest
          docker push $DOCKER_REPO:$IMAGE_TAG
          docker push $DOCKER_REPO:latest

      # Step 6: Deploy to Production using Ansible
      - name: Deploy to Production
        run: |
          scp ./k8s-deployment.yml ubuntu@13.218.75.13:/tmp/k8s-deployment.yml
          ansible-playbook -i ./inventory.ini ./deploy_k8s.yml
