name: CD Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-app:
    runs-on: [self-hosted, linux, x64]
   
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # --- SSH Setup (Required for Ansible to connect) ---
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY }}
         
      - name: Set up known hosts
        run: ssh-keyscan 54.146.176.115 >> ~/.ssh/known_hosts

      - name: Log in and Push Image to DockerHub (Task 4f)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
       
      - name: Push Images
        run: |
          DOCKER_REPO=khadijah332/weather-ml-app
          docker push $DOCKER_REPO:${{ github.sha }}
          docker push $DOCKER_REPO:latest

      # --- Deployment using Ansible (Task 4g) ---
      - name: Run Ansible Deploy Playbook (Task 4g)
        run: |
          # 1. Update the k8s manifest (located in root directory)
          sed -i 's|image: khadijah332/weather-ml-app:.*|image: khadijah332/weather-ml-app:latest|g' ../../k8s-deployment.yml
         
          # 2. Securely Copy the updated k8s manifest to the Production Server's /tmp directory
          scp ../../k8s-deployment.yml ubuntu@<PRODUCTION_SERVER_IP>:/tmp/k8s-deployment.yml
         
          # 3. Run the playbook (inventory.ini and deploy_k8s.yml must be in the project root)
          ansible-playbook -i ../../inventory.ini ../../deploy_k8s.yml
