name: CD Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Load SSH key for connecting to Production Server
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_KEY }}

      # Add Production server to known_hosts
      - name: Add Production Server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts

      # Login to DockerHub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build + Push Docker image
      - name: Build and push Docker image
        run: |
          DOCKER_REPO=khadijah332/weather-ml-app
          IMAGE_TAG=${{ github.sha }}
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest
          docker push $DOCKER_REPO:$IMAGE_TAG
          docker push $DOCKER_REPO:latest

      # Run Ansible Playbook
      - name: Deploy to Kubernetes via Ansible
        run: |
          ansible-playbook -i inventory.ini deploy_k8s.yml
