name: CI Workflow

on:
  push:
    branches:
      - main
      - master
      - bugfix

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: set PYTHONPATH for testing
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
      
      - name: Run Smoke Test
        run: python tests/smoke_test.py

      - name: Run Unit Test
        run: python tests/unit_test.py

      - name: Run Integration Test
        run: python tests/integration_test.py

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t khadijah332/weather-ml-app:$IMAGE_TAG .
          docker tag khadijah332/weather-ml-app:$IMAGE_TAG khadijah332/weather-ml-app:latest

      - name: Test Container Launch
        run: |
          docker run -d --name test-app khadijah332/weather-ml-app:latest
          sleep 5
          docker exec test-app ls /usr/src/app || ls /
          docker stop test-app
          docker rm test-app
